### PR TITLE
pairdrop-cli: add fallback if navigator.clipboard.readText() is not available

### LINKED ISSUE #62: Bug: Sharing via CLI doesn't work on Firefox
**Describe the bug**
The web app relies on the Clipboard API's [`readText`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText) method. Unfortunately, this method is not [available in Firefox except inside browser extensions](https://caniuse.com/?search=clipboard.readText).

Maybe instead of just failing it could display an autoselected textarea element to paste the text into? 

**To Reproduce**
1. Either share a larger file via the CLI or open the Pairdrop webpage with `?base64zip=paste` appended in Firefox
2. Click the button that says "Tap here to paste files"
3. Button vanished and popup appears that says "This feature is not available on your browser."

**Expected behavior**
The base64-encoded file is loaded into Pairdrop

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - Browser: Firefox 
 - Version: 110.0.1

**Self-Hosted**
Yes, but issue occurs on pairdrop.net as well.

**Self-Hosted Setup**
Proxy: Traefik 2.9
Deployment: docker compose/swarm

**Additional context**
None

### PR DESCRIPTION
**Pull request by schlagmichdoch**
fixes #62

### CODE REVIEW

File: public/scripts/ui.js [hunk 1]
```diff
@@ -1299,37 +1298,52 @@ class Base64ZipDialog extends Dialog {
...
+    preparePasting(type) {
+        if (navigator.clipboard.readText) {
+            this.$pasteBtn.innerText = `Tap here to paste ${type}`;
+            this.$pasteBtn.addEventListener('click', _ => this.processClipboard(type));
+        } else {
+            console.log("`navigator.clipboard.readText()` is not available on your browser.\nOn Firefox you can set `dom.events.asyncClipboard.readText` to true under `about:config` for convenience.")
+            this.$pasteBtn.setAttribute('hidden', '');
+            this.$fallbackTextarea.setAttribute('placeholder', `Paste here to send ${type}`);
+            this.$fallbackTextarea.removeAttribute('hidden');
+            this.$fallbackTextarea.addEventListener('input', e => this.processInput(e, type));
```
Comment (ChaosExAnima) [inline public/scripts/ui.js:1310]: Nit: either remove the event listener in `processClipboard`, declare the listener in the constructor, or use `once`.

**Review by ChaosExAnima — APPROVED** [review]
Tested locally and works great! Left a minor thing but otherwise 🚀

File: public/scripts/ui.js [hunk 2]
```diff
@@ -1299,37 +1298,52 @@ class Base64ZipDialog extends Dialog {
...
+            this.$fallbackTextarea.focus();
         }
+    }
 
-        this._setPasteBtnToProcessing();
+    async processInput(e, type) {
+        e.preventDefault();
```
Comment (schlagmichdoch) [inline public/scripts/ui.js:1316]: Nothing to prevent here. Remove event from method

File: public/scripts/ui.js (hunk 1 above)
Comment (schlagmichdoch) [reply public/scripts/ui.js:1310]: Just curious, is this mostly for tidiness or is there any consequence if I won’t remove it? For now this method is not ever called twice or is it?
Probably best to remove it anyways, especially if I add a possibility to overtake a session: #42

Comment (ChaosExAnima) [reply public/scripts/ui.js:1310]: Yeah, I figure just good practice to avoid creating a lot of duplicate event listeners. If that ever happens that'd lead to some odd bugs with multiple calls to `processInput`.

Comment (schlagmichdoch) [reply public/scripts/ui.js]: Did not know about the once option. Nice! I needed to remove the listeners manually though, otherwise a user could not interact anymore when accidentally clicking away of the btn or typing sth / pasting sth in the input that is not base64 encoded. Is added now and will be merged in a sec. Thanks for your help!
